# Generated by Django 2.0.3 on 2018-04-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='URL of the stored image')),
                ('description', models.CharField(help_text='Description of the image', max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('occupants', models.IntegerField(help_text='number of people staying')),
                ('check_in_date', models.DateTimeField(help_text='Date of check in')),
                ('check_out_date', models.DateTimeField(help_text='Date of check out')),
                ('payment', models.IntegerField(help_text='total expense of rooms')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_id',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Registration')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Type name of the room', max_length=50)),
                ('email', models.EmailField(help_text='Email address of user', max_length=254)),
                ('password', models.CharField(help_text='password of user', max_length=20)),
                ('user_type', models.CharField(choices=[('u', 'User'), ('a', 'Admin')], help_text='room availability',
                                               max_length=1)),
            ],
            options={
                'ordering': ['user_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.IntegerField(help_text='Enter the room number')),
                ('status', models.CharField(choices=[('o', 'Occupied'), ('a', 'Available'), ('r', 'Reserved')],
                                            help_text='room availability', max_length=1)),
            ],
            options={
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Type name of the room', max_length=50)),
                ('capacity', models.IntegerField(help_text='Number of people that can stay')),
                ('price', models.IntegerField(help_text='Price for one night')),
                ('has_wifi', models.BooleanField()),
                ('has_room_service', models.BooleanField()),
                ('has_breakfast', models.BooleanField()),
                ('has_shuttle_service', models.BooleanField()),
                ('has_spa', models.BooleanField()),
                ('has_mini_bar', models.BooleanField()),
                ('has_gym', models.BooleanField()),
                ('has_pool', models.BooleanField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Type'),
        ),
        migrations.AddField(
            model_name='registrationdetails',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Room'),
        ),
        migrations.AddField(
            model_name='registration',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.RestaurantUser'),
        ),
        migrations.AddField(
            model_name='images',
            name='room_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Type'),
        ),
    ]
