# Generated by Django 2.0.3 on 2018-04-23 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoteluserprofile',
            options={'ordering': ['id'], 'verbose_name': 'hotel User', 'verbose_name_plural': 'Hotel Users'},
        ),
    ]
