# Generated by Django 2.0.3 on 2018-04-22 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5')),
                ('review', models.CharField(help_text='Review description', max_length=200)),
                (
                'room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Room')),
                ('user_id',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.RestaurantUser')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
