# Generated by Django 2.0.3 on 2018-04-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantuser',
            name='user_type',
            field=models.CharField(choices=[('u', 'User'), ('a', 'Admin')], help_text='User type', max_length=1),
        ),
    ]
