# Generated by Django 2.0.3 on 2018-04-23 06:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0003_auto_20180422_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='url',
        ),
        migrations.RemoveField(
            model_name='type',
            name='has_shuttle_service',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Add room image', max_length=255),
        ),
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the room', max_length=200),
        ),
        migrations.AddField(
            model_name='type',
            name='has_air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='type',
            name='has_dryer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='type',
            name='has_electronic_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='images',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the image', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantuser',
            name='name',
            field=models.CharField(blank=True, help_text='Type name of the room', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurantuser',
            name='password',
            field=models.CharField(blank=True, help_text='password of user', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurantuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('u', 'User'), ('a', 'Admin')], help_text='User type',
                                   max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(blank=True, help_text='Review description', max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'Occupied'), ('a', 'Available'), ('r', 'Reserved')],
                                   help_text='room availability', max_length=1),
        ),
        migrations.AlterField(
            model_name='type',
            name='has_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='has_gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='has_mini_bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='has_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='has_room_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='has_spa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(blank=True, help_text='Type name of the room', max_length=50),
        ),
    ]
